# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 278e50a7d4517bcf12272c64a7933a13bd793aafd94796f78169222898e916c4d3564fde23f69d31b864e3cc48dde11469f04a45a625e7b6471c5ad0bbe58d59

test:
  secret_key_base: 40b0056f6445bb1ecd902ae17d9b1713528323694f1ea0373f5abc4c06b9732f3f71308a736609c50c12ea79ab667bdafc405cd49c73dcbb98c8dd6944c50d59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
